[workspace]
members = ["monolake", "monolake-core", "monolake-services"]
resolver = "2"

[workspace.dependencies]
monoio = "0.1.7"
monoio-http = "0.2.3"
monoio-http-client = "0.2.3"
monoio-native-tls = "0.1.0"
monoio-rustls = "0.1.5"
native-tls = "0.2"
service-async = "0.1.13"
certain-map = "0.2.4"
local-sync = "0.1"

[profile.release-lto]
inherits = "release"
lto = true
